### ISSUE TITLE
Azure Functions v2 .NET Core - ServiceBusTrigger Message not able to read BrokeredMessages

### ISSUE THREAD

**Issue by DiaAWAY** [Azure/azure-functions-servicebus-extension#13]
Hi!

We are attempting to upgrade our old ServiceBus solutions over to use the new .Net Core packages (both Azure Functions and Azure Webjobs).

When attempting to consume from our topics we encounter the following error:
`System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'message'. System.Private.CoreLib: Unable to translate bytes [99] at index 60 from specified code page to Unicode.`

This error occurs even if we attempt to use other types, such as _string_, _byte[]_ and _custom types_ (such as the standard _Message_ class).

The issue seems to be the following configuration:
_Body-Type: string
Content-Type: text/plain_

Other combinations seem to work properly (where none is empty Content-Type);
_stream+none, stream+text/plain and string+none_.

We may be able to circumvent this (untested) in our webjobs, as we can access _MessageReceiver_ or other ServiceBus configurations at runtime to handle this, but so far we have been unable to find any solution or method to handle this for Azure Functions as the framework throws an error before we are inside the function.

Is this behaviour a bug or by design?

Note: we do not control the creation of the servicebus messages, so we cannot simply change how we write the messages to the servicebus.

Edit: clarified that the exception occurs even with the standard Message class.

**Comment by alrod** [comment]
Can you please try to use:
Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch from: https://www.myget.org/feed/Packages/azure-appservice

It looks like the issue is fixed there.

**Comment by PlymouthRock** [comment]
Tried to install the beta package.  Won't install because dependent package Microsoft.Azure.WebJobs.Sources is missing from NuGet.

**Comment by arunhallan** [comment]
I get the same issue too when trying to pull down 3.1.0-beta4

**Comment by alrod** [comment]
Sorry for that. I added https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Sources

**Comment by marioleed** [comment]
Still doesn't work for me in 3.1.0-beta4.

**Comment by remartens** [comment]
The Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch from myget.org seems to do the trick. Any idea when this version will be released on NuGet?

**Comment by remartens** [comment]
Just after posting the last post, I noticed there is a new version on NuGet.... 3.1.0, but this version doesn't work. I guess it is based on the 3.10-beta4 from NuGet and not the 3.1.0-beta4-batch version on MyGet.

**Comment by alrod** [comment]
> Just after posting the last post, I noticed there is a new version on NuGet.... 3.1.0, but this version doesn't work. I guess it is based on the 3.10-beta4 from NuGet and not the 3.1.0-beta4-batch version on MyGet.

@remartens, you are right. Please use Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch from MyGet as workaround for now.

**Comment by marioleed** [comment]
When do you plan to release the 3.1.0-beta4-batch version on MyGet to NuGet?

**Comment by amandal1810** [comment]
version 3.1.1 is now on NuGet and upgrading to this resolved the issue 😄

**Comment by alrod** [comment]
@DiaAWAY, is 3.1.1 fixed the issue for you?

**Comment by DiaAWAY** [comment]
@alrod I'll check as soon as I am able :)

**Comment by DiaAWAY** [comment]
Upgrading _Microsoft.Azure.WebJobs.Extensions.ServiceBus_ to 3.1.1 did not change the issue :(
Still unable to consume service bus messages between these two service bus libraries.

**Sending:**
```
var client = TopicClient.CreateFromConnectionString(conStr);
client.Send(new BrokeredMessage("test")
    {
        ContentType = "text/plain"
    }
);
```

Package used when sending:
- WIndowsAzure.ServiceBus 3.1.1  (same result with 6.0.0)

**Receiving:**
```
public static class Function1
{
    [FunctionName("Function1")]
    public static void Run(
        [ServiceBusTrigger("mytopic", "mysubscription", Connection = "SbConStr")] 
        Message mySbMsg, 
        ILogger log)
    {
        log.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg.ToString()}");
    }
}
```
Packages used when receiving:
- Microsoft.Azure.ServiceBus 3.4.0
- Microsoft.Azure.WebJobs 3.0.10
- Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.1
- Microsoft.NET.Sdk.Functions 1.0.28

All of this was created using Visual Studio 2019 templates (.net 471 console for brokeredmessage, core 2.1 for functions).

Azure functions runtime:
_Azure Functions Core Tools (2.7.1846 Commit hash: 458c671341fda1c52bd46e1aa8943cb26e467830)
Function Runtime Version: 2.0.12858.0_

**Comment by remartens** [comment]
So when is this going to be fixed? Since November 19th there is version 4.0.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus on NuGet and it is still not working.

**Comment by alrod** [comment]
@DiaAWAY, the issue should be fixed in 4.1.0. Can you please check this?

**Comment by lars-nystrom-mio** [comment]
@alrod With `4.1.0` it seems to be failing when `ContentType` is empty (null) with the following message when it tries to deserialize to `Message`:
`System.Private.CoreLib: Exception while executing function: intimeresponse. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'mySbMsg'. Microsoft.Azure.WebJobs.ServiceBus: The Message with ContentType 'null' failed to deserialize to a string with the message: 'There was an error deserializing the object of type System.String. The input source is not correctly formatted.'. System.Private.DataContractSerialization: There was an error deserializing the object of type System.String. The input source is not correctly formatted. System.Private.DataContractSerialization: The input source is not correctly formatted.`

The `Run` function:
```
[FunctionName("myfunction")]
public static async Task Run(
    [ServiceBusTrigger("mytopic", "mysubscription", Connection = "sbconnection")]Message mySbMsg,
    ILogger log)       
{
    ...
}
```

The above still works in version `4.0.0`.

**Comment by grahambunce** [comment]
What's going on with this and why is it closed? This is definitely not fixed and is completely broken.

My Java clients are sending messages to Azure Service Bus - they set a content-type of "application/x-gzip". We cannot change this. These messages are gzipped before sending to the bus to save space (they can be large and blow out the size limitations unless we zip them).

My .NET Framework 4.7.x clients could read these fine and then we ran it through an unzip routine to get the content. No issues. We didn't use the Web Job framework as such but we did use the Azure Service Bus SDK.

This custom subscriber framework didn't port to .NET Core so we decided to use Web Job Service Bus extensions as a stepping stone to Azure Functions.

The Web Jobs fail with the error "The Message with ContentType 'application/x-gzip' failed to deserialize to a string with the message: 'There was an error deserializing the object of type System.String. The input source is not correctly formatted.'"

No matter *what* the signature to receive the object is: message, string, byte[] it will fail with the same error - there is *no way* to get this content into the web job for us to handle it.

This is pretty unbelievable  - not every publisher of a message is .NET - where on earth do we go with this??? Can we provide a custom deserializer somehow?

We're using the latest versions for everything:

"Microsoft.Azure.WebJobs" Version="3.0.14"
"Microsoft.Azure.WebJobs.Extensions" Version="3.0.6"
"Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.0"

**Comment by Jlopean** [comment]
so in the new world (.net 5 function Apps). we move away from [FunctionName("FunctionName")] to [Function("FunctionName")]

Additionally, you can no longer use 'Message' or Byte[]. it can only be a string!

 public async Task Run([ServiceBusTrigger(topicName, SubscriberName, Connection= %conn% )] string messageText, string id,  FunctionContext executionContext)

The magic now is in FunctionContext.

you can get the message properties from this e.g; executionContext.BindingContext.BindingData.Where(x => x.Key =="UserProperties")
